# Pywal theme for superfile
# Theme create by: https://github.com/slipstream8125
# Update by(sort by time):
#
# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "github-dark"

# ========= Border =========
file_panel_border = "{color6}"
sidebar_border = "{color6}"
footer_border = "{color6}"

# ========= Border Active =========
file_panel_border_active = "{color2}"
sidebar_border_active = "{color2}"
footer_border_active = "{color2}"
modal_border_active = "{color2}"

# ========= Background (bg) =========
full_screen_bg = "{background}"
file_panel_bg = "{background}" 
sidebar_bg = "{background}" 
footer_bg =  "{background}"
modal_bg = "{background}"

# ========= Foreground (fg) =========
full_screen_fg = "#B3B1AD"
file_panel_fg = "#B3B1AD"
sidebar_fg = "#B3B1AD"
footer_fg = "#B3B1AD"
modal_fg = "#B3B1AD"

# ========= Special Color =========
cursor = "{cursor}"
correct = "#AAD94C"
error = "#FF3333"
hint = "{color6}"
cancel = "#F07178"
# Gradient color can only have two colors!
gradient_color = ["{color6}", "{color3}"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "{color8}"
file_panel_top_path = "{color6}"
file_panel_item_selected_fg = "{color3}"
file_panel_item_selected_bg = "{background}"

# ========= Sidebar Special Items =========
sidebar_title = "{color6}"
sidebar_item_selected_fg = "{color2}"
sidebar_item_selected_bg = "{background}"
sidebar_divider = "{color2}"

# ========= Modal Special Items =========
modal_cancel_fg = "#0F1419"
modal_cancel_bg = "#F07178"

modal_confirm_fg = "#0F1419"
modal_confirm_bg = "#36A3D9"

# ========= Help Menu =========
help_menu_hotkey = "#36A3D9"
help_menu_title = "#F07178"
